#!/bin/bash
arm/Xtst -select 2 -enable 1 -us 1000 \
-init \
-echo "This tests r0 reads and writes" \
-echo "--->R0 write" \
-write 0xCff4 \
-write 0x0008 \
-write 0x0008 \
-echo "--->R0 should be Xff4" \
-echo "--->R0 write" \
-write 0x0004 \
-write 0x0008 \
-write 0x0008 \
-echo "--->R0 should be 0000" \

