#!/bin/bash
arm/Ftst \
-echo "This test cycles GPIO0 outputs (one at a time)" \
-write  0x4B01            \
-write  0x4C01            \
                          \
-usleep 1000000            \
-write  0x4B02            \
-write  0x4C02            \
                          \
-usleep 1000000            \
-write  0x4B04            \
-write  0x4C04            \
                          \
-usleep 1000000            \
-write  0x4B08            \
-write  0x4C08            \
                          \
-usleep 1000000            \
-write  0x4B10            \
-write  0x4C10            \
                          \
-usleep 1000000            \
-write  0x4B20            \
-write  0x4C20            \
                          \
-usleep 1000000            \
-write  0x4B00            \
-write  0x4C00            \

