#!/bin/bash
arm/Ftst \
-echo "This tests reads the system clock counter" \
-write  0x8f44            \
-write  0x0009            \
-echo   "Next value is valid" \
-write  0x0009            \
-write  0x0009            \
-write  0x0009            \
-write  0x0009            \
-write  0x0009            \
-write  0x0009            \
-write  0x0009            \
-write  0x0004            \

