#!/bin/bash
arm/Ftst \
-echo "This tests reads the sample clock counter" \
-write  0x8f54            \
-write  0x0009            \
-echo   "Next value is valid" \
-write  0x0009            \
-write  0x0009            \
-write  0x0009            \
-write  0x0009            \
-write  0x0009            \
-write  0x0009            \
-write  0x0009            \
-write  0x0004            \

