#!/bin/bash
arm/Ftst \
-echo "This tests r0 reads and writes" \
-echo "--->R0 write" \
-write 0xCff4 \
-write 0x0008 \
-write 0x0008 \
-echo "--->R0 should be Xff4" \
-echo "--->R0 write" \
-write 0x0004 \
-write 0x0008 \
-write 0x0008 \
-echo "--->R0 should be X004" \

