#!/bin/bash
arm/Ftst \
-echo "This test cycles LEDs" \
-write  0x8f04            \
-usleep 500000            \
-write  0x0f04            \
-usleep 500000            \
-write  0x0704            \
-usleep 500000            \
-write  0x0304            \
-usleep 500000            \
-write  0x0104            \
-usleep 500000            \
-write  0x0004            \
-usleep 500000            \
-write  0x0104            \
-usleep 500000            \
-write  0x0304            \
-usleep 500000            \
-write  0x0704            \
-usleep 500000            \
-write  0x0f04            \
-usleep 500000            \
-write  0x8f04            \
-usleep 500000            \
-write  0x0004            \

